apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-service
  labels:
    app: edge-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: edge-service
  template:
    metadata:
      labels:
        app: edge-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8000"
    spec:
      containers:
        - name: edge-service
          image: edge-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 5"]
          ports:
            - containerPort: 8000
          env:
#            - name: BPL_JVM_THREAD_COUNT
#              value: "50"
            - name: CATALOG_SERVICE_URL
              value: "http://catalog-service"
#            - name: SPRING_CLOUD_CONFIG_URI
#              value: http://config-service
            - name: ORDER_SERVICE_URL
              value: http://order-service
            - name: SPA_URL
              value: http://polar-ui
#            - name: REDIS_HOST
#              value: polar-redis
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 15
          volumeMounts:
            - name: edge-config-volume
              mountPath: /workspace/config
      volumes:
        - name: edge-config-volume
          configMap:
            name: edge-config

